title: "Nick Shrake's github page"
description: "Tutorials, experiments, and embedded systems writeups"

remote_theme: just-the-docs/just-the-docs
color_scheme: light

search_enabled: true
heading_anchors: true

nav_sort: case_insensitive
max_nav_depth: 2
toc_levels: 2..3

collections:
  projects:
    output: true
    permalink: /:collection/:path/