title: "Nick Shrake's github page"
description: "Tutorials, experiments, and embedded systems writeups"

theme: just-the-docs
color_scheme: light

search_enabled: true
heading_anchors: true

nav_sort: case_insensitive

collections:
  projects:
    output: true
    permalink: /:collection/:path/